# Generated by Django 5.2.1 on 2025-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('problem', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
