# Generated by Django 5.2.1 on 2025-05-26 03:13

import pybo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='제목없음', max_length=200)),
                ('difficulty', models.CharField(default='하', max_length=20)),
                ('problem', models.TextField(default='문제')),
                ('testCase', models.JSONField(default=pybo.models.default_testcase)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
